build: off

environment:
  matrix:
    - ARCH: amd64

install:
  - "cd eldstar_server"
  - ps: ".\\download_deps.ps1"
  - ps: ".\\build_deps.ps1"
  - "cd .."

build_script:
  - "cd eldstar_server"
  - ps: ".\\build.ps1"
  - "cd .."
  - ps: "Compress-Archive -Path 'eldstar_server/dists/*' -DestinationPath Eldstar_1.0.$(git rev-list --count HEAD)_WinDebug.zip"
  - "mkdir -p dists/32bit"
  - "cd dists/32bit"
  - ps: "Copy-Item ../../eldstar_client ./client -Recurse"
  - ps: "Copy-Item '../../eldstar_server/dists/Release - Visual Studio 15 2017/Release' ./server -Recurse"
  - ps: "Copy-Item ../../README.md ./README.md"
  - "cd ../.."
  - "mkdir -p dists/64bit"
  - "cd dists/64bit"
  - ps: "Copy-Item ../../eldstar_client ./client -Recurse"
  - ps: "Copy-Item '../../eldstar_server/dists/Release - Visual Studio 15 2017 Win64/Release' ./server -Recurse"
  - ps: "Copy-Item ../../README.md ./README.md"
  - "cd ../.."
  - ps: "Compress-Archive -Path 'dists/32bit/*' -DestinationPath Eldstar_1.0.$(git rev-list --count HEAD)_Win32.zip"
  - ps: "Compress-Archive -Path 'dists/64bit/*' -DestinationPath Eldstar_1.0.$(git rev-list --count HEAD)_Win64.zip"

artifacts:
  - path: Eldstar_*_Win32.zip
  - path: Eldstar_*_Win64.zip
  - path: Eldstar_*_WinDebug.zip
