build: off

image: Visual Studio 2019

environment:
  matrix:
    - ARCH: amd64
  CMAKE_GENERATOR: Visual Studio 16 2019

install:
  - "cd eldstar_server"
  - ps: ".\\download_deps.ps1"
  - ps: ".\\build_deps.ps1"
  - "cd .."

build_script:
  - "cd eldstar_server"
  - ps: ".\\build.ps1"
  - "cd .."
  - ps: "Compress-Archive -Path \"eldstar_server/dists/*\" -DestinationPath \"Eldstar_${env:APPVEYOR_REPO_TAG_NAME}_WinDebug.zip\""
  - ps: "Compress-Archive -Path \"eldstar_server/deps/*\" -DestinationPath \"Eldstar_${env:APPVEYOR_REPO_TAG_NAME}_WinDepends.zip\""
  - "mkdir dists\\32bit"
  - "cd dists/32bit"
  - ps: "Copy-Item ../../eldstar_client ./client -Recurse"
  - ps: "Copy-Item '../../eldstar_server/dists/Release - Win32/Release' ./server -Recurse"
  - ps: "Copy-Item ../../README.md ./README.md"
  - "cd ../.."
  - "mkdir dists\\64bit"
  - "cd dists/64bit"
  - ps: "Copy-Item ../../eldstar_client ./client -Recurse"
  - ps: "Copy-Item '../../eldstar_server/dists/Release - x64/Release' ./server -Recurse"
  - ps: "Copy-Item ../../README.md ./README.md"
  - "cd ../.."
  - ps: "Compress-Archive -Path \"dists/32bit/*\" -DestinationPath \"Eldstar_${env:APPVEYOR_REPO_TAG_NAME}_Win32.zip\""
  - ps: "Compress-Archive -Path \"dists/64bit/*\" -DestinationPath \"Eldstar_${env:APPVEYOR_REPO_TAG_NAME}_Win64.zip\""

artifacts:
  - path: Eldstar_*_Win32.zip
  - path: Eldstar_*_Win64.zip
  - path: Eldstar_*_WinDebug.zip
  - path: Eldstar_*_WinDepends.zip
